name: JS CI/CD

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore:
      - 'README.md'
      - '*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build & push Demo image
        uses: docker/build-push-action@v3
        with:
          context: CubismSdkForWeb-5-r.4
          file: CubismSdkForWeb-5-r.4/Dockerfile
          push: true
          tags: ghcr.io/lepora/movement/app:${{ github.sha }}
