name: JS CI/CD

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore:
      - 'README.md'
      - '*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build & push Demo image
        uses: docker/build-push-action@v3
        with:
          context: CubismSdkForWeb-5-r.4
          file: CubismSdkForWeb-5-r.4/Dockerfile
          push: true
          tags: ghcr.io/lepora/movement/app:${{ github.sha }}
